### ISSUE TITLE
some problem happen in the matlab scripts

### ISSUE THREAD

**Issue by WhiteH-coder** [czz-zzc/cordic-fft#1]
![image](https://github.com/user-attachments/assets/2b06ccae-e789-4847-a112-cb7511576666)
nothing change,just run the original scripts

**Comment by czz-zzc** [comment]
There's something wrong. I'll check it out tonight

**Comment by czz-zzc** [comment]
hello,
This is what I use for debugging, and it can be commented out.
I've submitted an updated version.
